"""
tests/unit/test_reports_stage.py
----------------------------------
Unit tests for analysis/reports/stage_report.py.

Covers:
  * generate_stage_text_report   — file written at correct 06_reports/05_per_stage/
    path; key sections, stage name, definition, prevalence, trend appear.
  * generate_all_stage_text_reports — one file per stage; stages with missing
    stage_id are skipped; empty list returns empty.
  * Filename slug: spaces and non-alnum characters become underscores.
  * Longitudinal trend direction words (increasing/decreasing/stable).
  * Degenerate inputs (empty exemplars, empty co_codes, zero prevalence).
"""

import os
import re
import sys
import shutil
import tempfile
import unittest

_QRA_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(_QRA_ROOT, 'src'))
if _QRA_ROOT not in sys.path: sys.path.insert(1, _QRA_ROOT)

import pandas as pd

from process import output_paths as _paths
from analysis.reports.stage_report import (
    generate_stage_text_report,
    generate_all_stage_text_reports,
)
from tests.testhelpers.fixtures import make_master_df


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

_FRAMEWORK = {
    0: {
        'short_name': 'Vigilance',
        'name': 'Vigilance (Dysappearing Body)',
        'definition': (
            'Attentional capture by pain signals; the body becomes a '
            'dysappearing obstacle that monopolizes awareness.'
        ),
    },
    1: {
        'short_name': 'Avoidance',
        'name': 'Avoidance (Experiential Escape)',
        'definition': 'Attentional skill deployed for experiential escape.',
    },
    2: {
        'short_name': 'Attention Regulation',
        'name': 'Attention Regulation (Volitional Presence)',
        'definition': 'Stable volitional presence with somatic experience.',
    },
    3: {
        'short_name': 'Metacognition',
        'name': 'Metacognition (Reflexive Observation)',
        'definition': 'Reflexive observation of mental processes.',
    },
    4: {
        'short_name': 'Reappraisal',
        'name': 'Reappraisal (Meaning Transformation)',
        'definition': 'Transformation of pain meaning and sensory structure.',
    },
}


def _make_stage_report(stage_id: int, trend: float = 0.01,
                       n_total: int = 100, n_stage: int = 30,
                       with_exemplars: bool = True,
                       with_codes: bool = True) -> dict:
    """Minimal per-stage analysis dict as generated by the analysis runner."""
    prev_by_session = {str(s): round(n_stage / n_total + s * 0.01, 3) for s in range(1, 5)}
    prev_by_participant = {'P01': 0.35, 'P02': 0.25, 'P03': 0.10}

    exemplars = []
    if with_exemplars:
        exemplars = [
            {
                'participant_id': 'P01',
                'session_id': 'c1s1',
                'confidence': 0.88,
                'text': f'This is a stage {stage_id} exemplar utterance about pain.',
                'justification': 'Clearly matches the stage definition.',
            },
            {
                'participant_id': 'P02',
                'session_id': 'c1s2',
                'confidence': 0.75,
                'text': f'Another stage {stage_id} exemplar about awareness.',
                'justification': '',
            },
        ]

    co_codes = []
    if with_codes:
        co_codes = [
            {'code_id': 'body_awareness', 'lift': 2.3, 'count': 14},
            {'code_id': 'present_moment', 'lift': 1.8, 'count': 9},
        ]

    return {
        'stage_id': stage_id,
        'overall_prevalence': n_stage / n_total,
        'n_segments_total': n_total,
        'n_segments_this_stage': n_stage,
        'longitudinal_trend': trend,
        'prevalence_by_session_number': prev_by_session,
        'prevalence_by_participant': prev_by_participant,
        'top_exemplars': exemplars,
        'co_occurring_codes': co_codes,
    }


# ---------------------------------------------------------------------------
# Tests for generate_stage_text_report
# ---------------------------------------------------------------------------

class TestStageTextReport(unittest.TestCase):

    def setUp(self):
        self.tmp = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _make_df(self) -> pd.DataFrame:
        return make_master_df(n_sessions=2, n_participants=2)

    def test_writes_file_to_correct_directory(self):
        df = self._make_df()
        sr = _make_stage_report(0)
        path = generate_stage_text_report(df, 0, _FRAMEWORK, sr, self.tmp)

        expected_dir = _paths.themes_dir(self.tmp)
        self.assertTrue(path.startswith(expected_dir),
                        f'Path {path!r} not under {expected_dir!r}')
        self.assertTrue(os.path.isfile(path))

    def test_filename_slug_for_vigilance(self):
        df = self._make_df()
        sr = _make_stage_report(0)
        path = generate_stage_text_report(df, 0, _FRAMEWORK, sr, self.tmp)
        self.assertEqual(os.path.basename(path), 'stage_vigilance.txt')

    def test_filename_slug_for_attention_regulation(self):
        """Multi-word short_name produces underscore-separated slug."""
        df = self._make_df()
        sr = _make_stage_report(2)
        path = generate_stage_text_report(df, 2, _FRAMEWORK, sr, self.tmp)
        self.assertEqual(os.path.basename(path), 'stage_attention_regulation.txt')

    def test_stage_name_and_definition_in_content(self):
        df = self._make_df()
        sr = _make_stage_report(0)
        path = generate_stage_text_report(df, 0, _FRAMEWORK, sr, self.tmp)
        content = open(path, encoding='utf-8').read()

        self.assertIn('Vigilance', content)
        self.assertIn('Attentional capture by pain', content)

    def test_full_name_in_header(self):
        df = self._make_df()
        sr = _make_stage_report(1)
        path = generate_stage_text_report(df, 1, _FRAMEWORK, sr, self.tmp)
        content = open(path, encoding='utf-8').read()
        self.assertIn('Avoidance (Experiential Escape)', content)

    def test_prevalence_rendered(self):
        df = self._make_df()
        sr = _make_stage_report(0, n_total=100, n_stage=30)
        path = generate_stage_text_report(df, 0, _FRAMEWORK, sr, self.tmp)
        content = open(path, encoding='utf-8').read()

        self.assertIn('30.0%', content)
        self.assertIn('30/100', content)

    def test_longitudinal_trend_increasing(self):
        df = self._make_df()
        sr = _make_stage_report(2, trend=0.05)
        path = generate_stage_text_report(df, 2, _FRAMEWORK, sr, self.tmp)
        content = open(path, encoding='utf-8').read()
        self.assertIn('increasing', content)

    def test_longitudinal_trend_decreasing(self):
        df = self._make_df()
        sr = _make_stage_report(0, trend=-0.05)
        path = generate_stage_text_report(df, 0, _FRAMEWORK, sr, self.tmp)
        content = open(path, encoding='utf-8').read()
        self.assertIn('decreasing', content)

    def test_longitudinal_trend_stable(self):
        df = self._make_df()
        sr = _make_stage_report(1, trend=0.0)
        path = generate_stage_text_report(df, 1, _FRAMEWORK, sr, self.tmp)
        content = open(path, encoding='utf-8').read()
        self.assertIn('stable', content)

    def test_prevalence_by_session_rendered(self):
        df = self._make_df()
        sr = _make_stage_report(0)
        path = generate_stage_text_report(df, 0, _FRAMEWORK, sr, self.tmp)
        content = open(path, encoding='utf-8').read()
        self.assertIn('Prevalence by Session', content)
        self.assertIn('Session 1', content)

    def test_prevalence_by_participant_rendered(self):
        df = self._make_df()
        sr = _make_stage_report(0)
        path = generate_stage_text_report(df, 0, _FRAMEWORK, sr, self.tmp)
        content = open(path, encoding='utf-8').read()
        self.assertIn('Prevalence by Participant', content)
        self.assertIn('P01', content)

    def test_exemplar_quotes_present(self):
        df = self._make_df()
        sr = _make_stage_report(0)
        path = generate_stage_text_report(df, 0, _FRAMEWORK, sr, self.tmp)
        content = open(path, encoding='utf-8').read()
        self.assertIn('Top Exemplar Quotes', content)
        self.assertIn('exemplar utterance about pain', content)

    def test_exemplar_justification_present(self):
        df = self._make_df()
        sr = _make_stage_report(0)
        path = generate_stage_text_report(df, 0, _FRAMEWORK, sr, self.tmp)
        content = open(path, encoding='utf-8').read()
        self.assertIn('Justification: Clearly matches the stage definition', content)

    def test_co_occurring_codes_rendered(self):
        df = self._make_df()
        sr = _make_stage_report(0)
        path = generate_stage_text_report(df, 0, _FRAMEWORK, sr, self.tmp)
        content = open(path, encoding='utf-8').read()
        self.assertIn('Co-occurring Codebook Codes', content)
        self.assertIn('body_awareness', content)
        self.assertIn('present_moment', content)

    def test_figure_reference_present(self):
        df = self._make_df()
        sr = _make_stage_report(2)
        path = generate_stage_text_report(df, 2, _FRAMEWORK, sr, self.tmp)
        content = open(path, encoding='utf-8').read()
        self.assertIn('stage_attention_regulation_prevalence.png', content)

    def test_empty_exemplars_no_crash(self):
        df = self._make_df()
        sr = _make_stage_report(0, with_exemplars=False)
        path = generate_stage_text_report(df, 0, _FRAMEWORK, sr, self.tmp)
        self.assertTrue(os.path.isfile(path))
        content = open(path, encoding='utf-8').read()
        # Top Exemplar Quotes section should be absent when list is empty
        self.assertNotIn('Top Exemplar Quotes', content)

    def test_empty_co_codes_no_crash(self):
        df = self._make_df()
        sr = _make_stage_report(0, with_codes=False)
        path = generate_stage_text_report(df, 0, _FRAMEWORK, sr, self.tmp)
        self.assertTrue(os.path.isfile(path))
        content = open(path, encoding='utf-8').read()
        # Co-occurring section absent when list is empty
        self.assertNotIn('Co-occurring Codebook Codes', content)

    def test_zero_prevalence_stage(self):
        """A stage with zero segments should still render without crashing."""
        df = self._make_df()
        sr = _make_stage_report(4, n_stage=0, n_total=100, trend=0.0,
                                with_exemplars=False, with_codes=False)
        sr['prevalence_by_session_number'] = {}
        sr['prevalence_by_participant'] = {}
        path = generate_stage_text_report(df, 4, _FRAMEWORK, sr, self.tmp)
        self.assertTrue(os.path.isfile(path))
        content = open(path, encoding='utf-8').read()
        self.assertIn('Reappraisal', content)
        self.assertIn('0.0%', content)

    def test_all_five_stages_produce_distinct_files(self):
        df = self._make_df()
        paths = []
        for stage_id in range(5):
            sr = _make_stage_report(stage_id)
            path = generate_stage_text_report(df, stage_id, _FRAMEWORK, sr, self.tmp)
            paths.append(path)

        # All paths distinct
        self.assertEqual(len(set(paths)), 5)
        # All files exist
        for p in paths:
            self.assertTrue(os.path.isfile(p), f'Missing: {p}')


# ---------------------------------------------------------------------------
# Tests for generate_all_stage_text_reports
# ---------------------------------------------------------------------------

class TestGenerateAllStageTextReports(unittest.TestCase):

    def setUp(self):
        self.tmp = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _make_df(self) -> pd.DataFrame:
        return make_master_df(n_sessions=2, n_participants=2)

    def test_generates_one_file_per_stage(self):
        df = self._make_df()
        stage_reports = [_make_stage_report(i) for i in range(5)]

        paths = generate_all_stage_text_reports(df, _FRAMEWORK, stage_reports, self.tmp)

        self.assertEqual(len(paths), 5)
        for p in paths:
            self.assertTrue(os.path.isfile(p), f'Missing: {p}')

    def test_skips_entries_without_stage_id(self):
        df = self._make_df()
        good = _make_stage_report(0)
        bad = {'overall_prevalence': 0.2}  # no stage_id key

        paths = generate_all_stage_text_reports(df, _FRAMEWORK, [bad, good], self.tmp)
        self.assertEqual(len(paths), 1)

    def test_empty_list_returns_empty(self):
        df = self._make_df()
        paths = generate_all_stage_text_reports(df, _FRAMEWORK, [], self.tmp)
        self.assertEqual(paths, [])

    def test_partial_framework_only_matching_stages_written(self):
        """Only stages present in stage_reports are written; framework keys irrelevant."""
        df = self._make_df()
        # Only supply stages 0 and 2
        stage_reports = [_make_stage_report(0), _make_stage_report(2)]

        paths = generate_all_stage_text_reports(df, _FRAMEWORK, stage_reports, self.tmp)
        self.assertEqual(len(paths), 2)
        basenames = {os.path.basename(p) for p in paths}
        self.assertIn('stage_vigilance.txt', basenames)
        self.assertIn('stage_attention_regulation.txt', basenames)


if __name__ == '__main__':
    unittest.main()
